# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QCheckBox, QFrame,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSpacerItem, QSplitter, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1316, 700)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionReset = QAction(MainWindow)
        self.actionReset.setObjectName(u"actionReset")
        self.actionGCode = QAction(MainWindow)
        self.actionGCode.setObjectName(u"actionGCode")
        self.actionCode = QAction(MainWindow)
        self.actionCode.setObjectName(u"actionCode")
        self.actionCurrent_Port = QAction(MainWindow)
        self.actionCurrent_Port.setObjectName(u"actionCurrent_Port")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionPorts = QAction(MainWindow)
        self.actionPorts.setObjectName(u"actionPorts")
        self.actionCalibrate = QAction(MainWindow)
        self.actionCalibrate.setObjectName(u"actionCalibrate")
        self.styleSheet = QWidget(MainWindow)
        self.styleSheet.setObjectName(u"styleSheet")
        self.styleSheet.setStyleSheet(u"")
        self.horizontalLayout = QHBoxLayout(self.styleSheet)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.left_side = QFrame(self.styleSheet)
        self.left_side.setObjectName(u"left_side")
        self.left_side.setMinimumSize(QSize(200, 0))
        self.left_side.setMaximumSize(QSize(200, 16777215))
        self.left_side.setFrameShape(QFrame.StyledPanel)
        self.left_side.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.left_side)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.top_left_split = QSplitter(self.left_side)
        self.top_left_split.setObjectName(u"top_left_split")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_left_split.sizePolicy().hasHeightForWidth())
        self.top_left_split.setSizePolicy(sizePolicy)
        self.top_left_split.setMinimumSize(QSize(110, 0))
        self.top_left_split.setMaximumSize(QSize(16777215, 63))
        self.top_left_split.setOrientation(Qt.Vertical)
        self.disablemotors = QPushButton(self.top_left_split)
        self.disablemotors.setObjectName(u"disablemotors")
        self.top_left_split.addWidget(self.disablemotors)
        self.autohome = QPushButton(self.top_left_split)
        self.autohome.setObjectName(u"autohome")
        self.top_left_split.addWidget(self.autohome)

        self.verticalLayout_3.addWidget(self.top_left_split)

        self.splitter = QSplitter(self.left_side)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Vertical)
        self.well_split = QSplitter(self.splitter)
        self.well_split.setObjectName(u"well_split")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.well_split.sizePolicy().hasHeightForWidth())
        self.well_split.setSizePolicy(sizePolicy1)
        self.well_split.setOrientation(Qt.Horizontal)
        self.sel_well = QCheckBox(self.well_split)
        self.buttonGroup = QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.sel_well)
        self.sel_well.setObjectName(u"sel_well")
        self.sel_well.setAutoExclusive(True)
        self.well_split.addWidget(self.sel_well)
        self.well_edit = QLineEdit(self.well_split)
        self.well_edit.setObjectName(u"well_edit")
        self.well_edit.setMinimumSize(QSize(93, 0))
        self.well_edit.setMaximumSize(QSize(93, 16777215))
        self.well_split.addWidget(self.well_edit)
        self.splitter.addWidget(self.well_split)
        self.row_split = QSplitter(self.splitter)
        self.row_split.setObjectName(u"row_split")
        sizePolicy1.setHeightForWidth(self.row_split.sizePolicy().hasHeightForWidth())
        self.row_split.setSizePolicy(sizePolicy1)
        self.row_split.setOrientation(Qt.Horizontal)
        self.sel_row = QCheckBox(self.row_split)
        self.buttonGroup.addButton(self.sel_row)
        self.sel_row.setObjectName(u"sel_row")
        self.sel_row.setAutoExclusive(True)
        self.row_split.addWidget(self.sel_row)
        self.row_edit = QLineEdit(self.row_split)
        self.row_edit.setObjectName(u"row_edit")
        self.row_edit.setMaximumSize(QSize(93, 16777215))
        self.row_split.addWidget(self.row_edit)
        self.splitter.addWidget(self.row_split)
        self.all_split = QSplitter(self.splitter)
        self.all_split.setObjectName(u"all_split")
        sizePolicy1.setHeightForWidth(self.all_split.sizePolicy().hasHeightForWidth())
        self.all_split.setSizePolicy(sizePolicy1)
        self.all_split.setOrientation(Qt.Horizontal)
        self.sel_all = QCheckBox(self.all_split)
        self.buttonGroup.addButton(self.sel_all)
        self.sel_all.setObjectName(u"sel_all")
        self.sel_all.setAutoExclusive(True)
        self.all_split.addWidget(self.sel_all)
        self.splitter.addWidget(self.all_split)

        self.verticalLayout_3.addWidget(self.splitter)

        self.run_stop_split = QSplitter(self.left_side)
        self.run_stop_split.setObjectName(u"run_stop_split")
        self.run_stop_split.setMinimumSize(QSize(176, 0))
        self.run_stop_split.setMaximumSize(QSize(16777215, 96))
        self.run_stop_split.setOrientation(Qt.Vertical)
        self.est_time = QLineEdit(self.run_stop_split)
        self.est_time.setObjectName(u"est_time")
        self.est_time.setReadOnly(True)
        self.run_stop_split.addWidget(self.est_time)
        self.run = QPushButton(self.run_stop_split)
        self.run.setObjectName(u"run")
        self.run_stop_split.addWidget(self.run)
        self.stop = QPushButton(self.run_stop_split)
        self.stop.setObjectName(u"stop")
        self.run_stop_split.addWidget(self.stop)

        self.verticalLayout_3.addWidget(self.run_stop_split)


        self.horizontalLayout.addWidget(self.left_side)

        self.middle = QFrame(self.styleSheet)
        self.middle.setObjectName(u"middle")
        self.middle.setMinimumSize(QSize(780, 0))
        self.middle.setMaximumSize(QSize(780, 16777215))
        self.middle.setFrameShape(QFrame.StyledPanel)
        self.middle.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.middle)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label = QLabel(self.middle)
        self.label.setObjectName(u"label")
        self.label.setTextFormat(Qt.PlainText)
        self.label.setPixmap(QPixmap(u"images/well_plate.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.progress_bar = QProgressBar(self.middle)
        self.progress_bar.setObjectName(u"progress_bar")
        sizePolicy1.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy1)
        self.progress_bar.setMinimumSize(QSize(0, 50))
        self.progress_bar.setMaximumSize(QSize(16777215, 50))
        self.progress_bar.setValue(24)

        self.verticalLayout_2.addWidget(self.progress_bar)


        self.horizontalLayout.addWidget(self.middle)

        self.right_side = QFrame(self.styleSheet)
        self.right_side.setObjectName(u"right_side")
        self.right_side.setMinimumSize(QSize(300, 0))
        self.right_side.setMaximumSize(QSize(300, 16777215))
        self.right_side.setFrameShape(QFrame.StyledPanel)
        self.right_side.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.right_side)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.control_split = QSplitter(self.right_side)
        self.control_split.setObjectName(u"control_split")
        self.control_split.setMinimumSize(QSize(265, 0))
        self.control_split.setMaximumSize(QSize(16777215, 162))
        self.control_split.setOrientation(Qt.Vertical)
        self.home_split = QSplitter(self.control_split)
        self.home_split.setObjectName(u"home_split")
        self.home_split.setOrientation(Qt.Horizontal)
        self.x_home = QPushButton(self.home_split)
        self.x_home.setObjectName(u"x_home")
        self.home_split.addWidget(self.x_home)
        self.y_home = QPushButton(self.home_split)
        self.y_home.setObjectName(u"y_home")
        self.home_split.addWidget(self.y_home)
        self.z_home = QPushButton(self.home_split)
        self.z_home.setObjectName(u"z_home")
        self.home_split.addWidget(self.z_home)
        self.control_split.addWidget(self.home_split)
        self.move_man_split = QSplitter(self.control_split)
        self.move_man_split.setObjectName(u"move_man_split")
        self.move_man_split.setOrientation(Qt.Horizontal)
        self.manual_split = QSplitter(self.move_man_split)
        self.manual_split.setObjectName(u"manual_split")
        self.manual_split.setOrientation(Qt.Vertical)
        self.x_split = QSplitter(self.manual_split)
        self.x_split.setObjectName(u"x_split")
        self.x_split.setOrientation(Qt.Horizontal)
        self.x_label = QLabel(self.x_split)
        self.x_label.setObjectName(u"x_label")
        self.x_split.addWidget(self.x_label)
        self.x_input = QLineEdit(self.x_split)
        self.x_input.setObjectName(u"x_input")
        self.x_split.addWidget(self.x_input)
        self.manual_split.addWidget(self.x_split)
        self.y_split = QSplitter(self.manual_split)
        self.y_split.setObjectName(u"y_split")
        self.y_split.setOrientation(Qt.Horizontal)
        self.y_label = QLabel(self.y_split)
        self.y_label.setObjectName(u"y_label")
        self.y_split.addWidget(self.y_label)
        self.y_input = QLineEdit(self.y_split)
        self.y_input.setObjectName(u"y_input")
        self.y_split.addWidget(self.y_input)
        self.manual_split.addWidget(self.y_split)
        self.z_split = QSplitter(self.manual_split)
        self.z_split.setObjectName(u"z_split")
        self.z_split.setOrientation(Qt.Horizontal)
        self.z_label = QLabel(self.z_split)
        self.z_label.setObjectName(u"z_label")
        self.z_split.addWidget(self.z_label)
        self.z_input = QLineEdit(self.z_split)
        self.z_input.setObjectName(u"z_input")
        self.z_split.addWidget(self.z_input)
        self.manual_split.addWidget(self.z_split)
        self.move_man_split.addWidget(self.manual_split)
        self.commit = QPushButton(self.move_man_split)
        self.commit.setObjectName(u"commit")
        self.move_man_split.addWidget(self.commit)
        self.control_split.addWidget(self.move_man_split)
        self.home_set_split = QSplitter(self.control_split)
        self.home_set_split.setObjectName(u"home_set_split")
        self.home_set_split.setOrientation(Qt.Horizontal)
        self.x_set = QPushButton(self.home_set_split)
        self.x_set.setObjectName(u"x_set")
        self.home_set_split.addWidget(self.x_set)
        self.y_set = QPushButton(self.home_set_split)
        self.y_set.setObjectName(u"y_set")
        self.home_set_split.addWidget(self.y_set)
        self.z_set = QPushButton(self.home_set_split)
        self.z_set.setObjectName(u"z_set")
        self.home_set_split.addWidget(self.z_set)
        self.control_split.addWidget(self.home_set_split)

        self.verticalLayout.addWidget(self.control_split)

        self.speed_split = QSplitter(self.right_side)
        self.speed_split.setObjectName(u"speed_split")
        sizePolicy.setHeightForWidth(self.speed_split.sizePolicy().hasHeightForWidth())
        self.speed_split.setSizePolicy(sizePolicy)
        self.speed_split.setMinimumSize(QSize(265, 0))
        self.speed_split.setMaximumSize(QSize(16777215, 94))
        self.speed_split.setOrientation(Qt.Horizontal)
        self.man_speed_split = QSplitter(self.speed_split)
        self.man_speed_split.setObjectName(u"man_speed_split")
        sizePolicy1.setHeightForWidth(self.man_speed_split.sizePolicy().hasHeightForWidth())
        self.man_speed_split.setSizePolicy(sizePolicy1)
        self.man_speed_split.setMinimumSize(QSize(150, 0))
        self.man_speed_split.setMaximumSize(QSize(16777215, 94))
        self.man_speed_split.setOrientation(Qt.Vertical)
        self.x_speed_split = QSplitter(self.man_speed_split)
        self.x_speed_split.setObjectName(u"x_speed_split")
        self.x_speed_split.setOrientation(Qt.Horizontal)
        self.x_speed_lab = QLabel(self.x_speed_split)
        self.x_speed_lab.setObjectName(u"x_speed_lab")
        self.x_speed_split.addWidget(self.x_speed_lab)
        self.x_speed = QLineEdit(self.x_speed_split)
        self.x_speed.setObjectName(u"x_speed")
        self.x_speed_split.addWidget(self.x_speed)
        self.man_speed_split.addWidget(self.x_speed_split)
        self.y_speed_split = QSplitter(self.man_speed_split)
        self.y_speed_split.setObjectName(u"y_speed_split")
        self.y_speed_split.setOrientation(Qt.Horizontal)
        self.y_speed_lab = QLabel(self.y_speed_split)
        self.y_speed_lab.setObjectName(u"y_speed_lab")
        self.y_speed_split.addWidget(self.y_speed_lab)
        self.y_speed = QLineEdit(self.y_speed_split)
        self.y_speed.setObjectName(u"y_speed")
        self.y_speed_split.addWidget(self.y_speed)
        self.man_speed_split.addWidget(self.y_speed_split)
        self.z_speed_split = QSplitter(self.man_speed_split)
        self.z_speed_split.setObjectName(u"z_speed_split")
        self.z_speed_split.setOrientation(Qt.Horizontal)
        self.z_speed_lab = QLabel(self.z_speed_split)
        self.z_speed_lab.setObjectName(u"z_speed_lab")
        self.z_speed_split.addWidget(self.z_speed_lab)
        self.z_speed = QLineEdit(self.z_speed_split)
        self.z_speed.setObjectName(u"z_speed")
        self.z_speed_split.addWidget(self.z_speed)
        self.man_speed_split.addWidget(self.z_speed_split)
        self.speed_split.addWidget(self.man_speed_split)
        self.speed_set = QPushButton(self.speed_split)
        self.speed_set.setObjectName(u"speed_set")
        self.speed_split.addWidget(self.speed_set)

        self.verticalLayout.addWidget(self.speed_split)

        self.gcode_split = QSplitter(self.right_side)
        self.gcode_split.setObjectName(u"gcode_split")
        sizePolicy1.setHeightForWidth(self.gcode_split.sizePolicy().hasHeightForWidth())
        self.gcode_split.setSizePolicy(sizePolicy1)
        self.gcode_split.setMinimumSize(QSize(110, 0))
        self.gcode_split.setMaximumSize(QSize(16777215, 63))
        self.gcode_split.setOrientation(Qt.Vertical)
        self.load_gcode = QPushButton(self.gcode_split)
        self.load_gcode.setObjectName(u"load_gcode")
        self.gcode_split.addWidget(self.load_gcode)
        self.edit_gcode = QPushButton(self.gcode_split)
        self.edit_gcode.setObjectName(u"edit_gcode")
        self.gcode_split.addWidget(self.edit_gcode)

        self.verticalLayout.addWidget(self.gcode_split)


        self.horizontalLayout.addWidget(self.right_side)

        MainWindow.setCentralWidget(self.styleSheet)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1316, 25))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionReset)
        self.menuHelp.addAction(self.actionGCode)
        self.menuHelp.addAction(self.actionCode)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuSettings.addAction(self.actionPorts)
        self.menuSettings.addAction(self.actionCalibrate)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionReset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.actionGCode.setText(QCoreApplication.translate("MainWindow", u"GCode", None))
        self.actionCode.setText(QCoreApplication.translate("MainWindow", u"Code", None))
        self.actionCurrent_Port.setText(QCoreApplication.translate("MainWindow", u"Current Port:", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"Available Ports:", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindow", u"Documentation", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
        self.actionPorts.setText(QCoreApplication.translate("MainWindow", u"Ports", None))
        self.actionCalibrate.setText(QCoreApplication.translate("MainWindow", u"Calibrate", None))
        self.disablemotors.setText(QCoreApplication.translate("MainWindow", u"Disable Motors", None))
        self.autohome.setText(QCoreApplication.translate("MainWindow", u"Auto Home", None))
        self.sel_well.setText(QCoreApplication.translate("MainWindow", u"By Well", None))
        self.sel_row.setText(QCoreApplication.translate("MainWindow", u"By Row", None))
        self.sel_all.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.est_time.setText(QCoreApplication.translate("MainWindow", u"Estimated Time:", None))
        self.run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label.setText("")
        self.x_home.setText(QCoreApplication.translate("MainWindow", u"X Home", None))
        self.y_home.setText(QCoreApplication.translate("MainWindow", u"Y Home", None))
        self.z_home.setText(QCoreApplication.translate("MainWindow", u"Z Home", None))
        self.x_label.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.y_label.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.z_label.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.commit.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.x_set.setText(QCoreApplication.translate("MainWindow", u"X Home Set", None))
        self.y_set.setText(QCoreApplication.translate("MainWindow", u"Y Home Set", None))
        self.z_set.setText(QCoreApplication.translate("MainWindow", u"Z Home Set", None))
        self.x_speed_lab.setText(QCoreApplication.translate("MainWindow", u"X Speed", None))
        self.y_speed_lab.setText(QCoreApplication.translate("MainWindow", u"Y Speed", None))
        self.z_speed_lab.setText(QCoreApplication.translate("MainWindow", u"Z Speed", None))
        self.speed_set.setText(QCoreApplication.translate("MainWindow", u"Set Speed", None))
        self.load_gcode.setText(QCoreApplication.translate("MainWindow", u"Load Gcode", None))
        self.edit_gcode.setText(QCoreApplication.translate("MainWindow", u"Edit Gcode", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

